/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gui;

import com.model.BankAccount;
import javax.swing.JOptionPane;


/**
 *
 * @author Nann
 */
public class displayApp extends javax.swing.JFrame {

    /**
     * Creates new form displayApp_profile
     */
    public displayApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        logoutBTT = new javax.swing.JButton();
        depositButton = new javax.swing.JButton();
        withdrawBTT = new javax.swing.JButton();
        createAccButton = new javax.swing.JButton();
        statementPrintBTT = new javax.swing.JButton();
        transferAccBTT = new javax.swing.JButton();
        interestButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Profile");
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        getContentPane().setLayout(null);

        logoutBTT.setText("Log out");
        logoutBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTTActionPerformed(evt);
            }
        });
        getContentPane().add(logoutBTT);
        logoutBTT.setBounds(170, 200, 170, 100);

        depositButton.setText("Deposit");
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });
        getContentPane().add(depositButton);
        depositButton.setBounds(170, 100, 170, 100);

        withdrawBTT.setText("Withdraw");
        withdrawBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBTTActionPerformed(evt);
            }
        });
        getContentPane().add(withdrawBTT);
        withdrawBTT.setBounds(0, 100, 170, 100);

        createAccButton.setText("Create account");
        createAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccButtonActionPerformed(evt);
            }
        });
        getContentPane().add(createAccButton);
        createAccButton.setBounds(0, 200, 170, 100);

        statementPrintBTT.setText("Statemant Print");
        statementPrintBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statementPrintBTTActionPerformed(evt);
            }
        });
        getContentPane().add(statementPrintBTT);
        statementPrintBTT.setBounds(0, 0, 170, 50);

        transferAccBTT.setText("Transfer<account>");
        transferAccBTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAccBTTActionPerformed(evt);
            }
        });
        getContentPane().add(transferAccBTT);
        transferAccBTT.setBounds(170, 0, 170, 100);

        interestButton.setText("Interest");
        interestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interestButtonActionPerformed(evt);
            }
        });
        getContentPane().add(interestButton);
        interestButton.setBounds(0, 50, 170, 50);

        setSize(new java.awt.Dimension(346, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTTActionPerformed
        // TODO add your handling code here:
        
            if(!call.useConfirmDialog("cancel","Are you sure")){
                setVisible(true);
            }else{
                call.callEmpLogin();
                
                setVisible(false);
            }
    }//GEN-LAST:event_logoutBTTActionPerformed

    private void withdrawBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBTTActionPerformed
        // TODO add your handling code here:
        call.callWithDrawal();
        setVisible(false);
        
    }//GEN-LAST:event_withdrawBTTActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        call.callDeposit();
        setVisible(false);
    }//GEN-LAST:event_depositButtonActionPerformed

    private void createAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccButtonActionPerformed
        // TODO add your handling code here:
        call.callCreateAccount();
        setVisible(false);
    }//GEN-LAST:event_createAccButtonActionPerformed

    private void statementPrintBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statementPrintBTTActionPerformed
        // TODO add your handling code here:
        call.callStatementPrintout();
        setVisible(false);
    }//GEN-LAST:event_statementPrintBTTActionPerformed

    private void transferAccBTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAccBTTActionPerformed
        // TODO add your handling code here:
        call.callTransferAccount();
        setVisible(false);
    }//GEN-LAST:event_transferAccBTTActionPerformed

    private void interestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interestButtonActionPerformed
        // TODO add your handling code here:
        call.callInterest();
        setVisible(false);
    }//GEN-LAST:event_interestButtonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(displayApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(displayApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(displayApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(displayApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new displayApp().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton createAccButton;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton interestButton;
    private javax.swing.JButton logoutBTT;
    private javax.swing.JButton statementPrintBTT;
    private javax.swing.JButton transferAccBTT;
    private javax.swing.JButton withdrawBTT;
    // End of variables declaration//GEN-END:variables
}
